import React, { useEffect } from "react";
import { useAtom } from "jotai";
import AsideBase from "../../components/layout/AsideBase";
import { sideActiveLink } from "../../components/context/store";
import { Button } from "@mantine/core";
import { showNotification } from "@mantine/notifications";
import { anyTalkLink } from "../utils/links";
import Head from "next/head";
import Link from "next/link";

type Props = {};

const index = (props: Props) => {
  const [link] = useAtom(sideActiveLink);

  const links = ["Security", "Settings", "Dashboard", "Releases", "Account"];

  useEffect(() => {
    console.log(link);
  }, [link]);
  return (
    <>
      <Head>
        <title>Has-Labs Works</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Has <span className="text-[hsl(280,100%,70%)]">Labs</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/anytalk"
            >
              <h3 className="text-2xl font-bold">AnyTalk →</h3>
              <div className="text-lg">
                Social Media Application that has many features like any others
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/"
            >
              <h3 className="text-2xl font-bold">Unknown →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default index;
